server:
  port: 80
  servlet:
    context-path:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mappers/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring:
  profiles:
    active: dev
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    time-zone: GMT+8
    default-property-inclusion: non_null
wechat:
  cp:
    corpId: ww7cab60eed263f4ad
    appConfigs:
      - agentId: 1000054
        secret: 1j59ezsl50EZ9FDbE9TIjEG55OcTh7YIdgkV2axcW6Q
        token: 6NJy1pQMYe4
        aesKey: v8GIRONpcI8a3mjhZ9i7IwJpUsKKtMBdfni8JVGaR7V