server:
  port: 80
  servlet:
    context-path:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mappers/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring:
  profiles:
    active: dev
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    time-zone: GMT+8
    default-property-inclusion: non_null